var GAME_LEVELS = [
  ["!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "vxxxxxxxxxxxxxxxxxxxxvxxxxxxxxxxxvxxxxxxxxxxxxxxxxxxxxxxvxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                s                        o                                      ",
   "             xxxx         o            xxxxx                                    ",
   "             x         xxxxxxx    xxxxxx   x     s                              ",
   "             x  o                          xxxxxxxxxxxx                         ",
   "             xxxxxxx                                                            ",
   "                                                         xxxxx                  ",
   "                                                                                ",
   "                                                                  xxxxxx      s ",
   "                                            o               o               xxxx",
   "              s                                           xxxxx                x",
   "             xxxx                           s                                  x",
   "o            x  x                        xxxxxx                            o   x",
   "x            x  x                                                  s           x",
   "x    @     xxx  x      =     xx         o   o   o                xxxxx         x",
   "xxxxxxxxxxxx    xxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxx     xxxxxxxx   xxxxxxxxxxx",
   "                              x     x               x     x                     ",
   "                              x!!!!!x               x!!!!!x                     ",
   "                              x!!!!!x               x!!!!!x                     ",
   "                              xxxxxxx               xxxxxxx                     ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                                  ",
   "      @                                                                                                           ",
   "x          x                 xxxxxxxxxx                                                                           ",
   "x          x                 x        x                                                                           ",
   "x     o    x                 x   o    x                                                                           ",
   "x          x                 xxs     xx                                                                           ",
   "xx        xx          |       xx     x                 |            |                            |         |      ",
   "!x        x!!!!!!!!!!!!!!!!!!!x      x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!x        xxxxvxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!",
   "!x        xx                                    xxxxxxxxxxxxxxxx!!!!!!!!!!x               xx!!!!!!!!!!!!!!!!!!!!!!",
   "!x    o   xx            o                       x             xx!!!!!!!!!!x    o           x!!!!!!!!!!!!!!!!!!!!!!",
   "!x        xx      xxxxxxxxxxxxxxxxxxxx          x     o        xxxxvxxxxxxx                xxvxxxxxxxxxxxxx!!!!!!!",
   "!x        xxo    xx!!!!!!!!!!!!!!!!!!x          xs                                                        x!!!!!!!",
   "!x        xxx    x!!xxxxxxxxvxxxxxxxxx          xx    xxxxxxx                                             xxx!!!!!",
   "!x        xx     x!!x                            xx         x               xxxxxxxxxx                    xxx!!!!!",
   "!x        xx    xx!!x                             xx        xx             xx!!!!x                         =x!!!!!",
   "!x        xx     x!!x  o              xxxx         x               o      xx!!!!!xxxxxx                    xx!!!!!",
   "!xx      xxx     x!!xxxxxx   xxxxxxxxxx            xx                    xx!!!!!!xxxx                      =x!!!!!",
   "!!x      x!xx    x!!!!!!!!x  x!!!!!!!!x            x       s  xxxxxxxxxxxx!!!!!!!xx                        =x!!!!!",
   "!!x      x!x    ox!!!!!!!!x  x!!!!!!!!x            x    xxxxxxx!!!!!!!!!!!!!!!!!!xxx                  xxxxxxx!!!!!",
   "!!x   o  x!x    xx!!!!!!!!x  x!!!!!!!!x      o     xo    x!!!!!!!!!!!!!!!!!!!!!!!xxxx                      =x!!!!!",
   "!!x      x!x     x!!!!!!!!x  x!!!!xxxxx            xx    x!!!!!!!!!!!!!!!!!!!!!!!xxxxx                     =x!!!!!",
   "!!x      x!x     x!!!!!!!!xxxx!!!!x                x    ox!!!!!!!!!!!!!!!!!!!!!!!xxxxxx              xxxxxxxx!!!!!",
   "!!x      x!xx    x!!!!!!!!!!!!xxvxx               xx    xx!!!!!!!!!!!!!!!!!!!!!!!xxxxxxx           xxxxxxxxxx!!!!!",
   "!!x      x!x     x!!!!!!xxxxxxx                          x!!!!!!!!xxxxxxxxxxxxxxxxxxx                      =x!!!!!",
   "!!x      xxx    xx!!!!!!x                                x!!!!!!!!x                                         x!!!!!",
   "!!x              x!!!!!!x   o                      xxxxxxx!!!!!!!!x    o              o     o   o     o     x!!!!!",
   "!!x      o       x!!!!!!x               s          x!!!!!!!!!!!!!!x          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!",
   "!!xxxxxxxxxxxxxxxx!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!xxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["xxxxxxxxxx                                                                                                        ",
   "x!!!!!!!!x                                                                                                        ",
   "xx!!!!!xx                                                                                             s       o   ",
   " xxxvxxx                                                                                         xxxxxxxxxxxxxxxxx",
   "                                                                                               xxx!!!!!!!!!!!!!!!!",
   "                                                                                            xxxx!!!!!!!!!!!!!!!!!!",
   "                                                                                        xxxxx!!!!!!!!!!!!!!!!!!!!!",
   "                                                                                      xxx!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                                                 xxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                                            xxxxxx x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                                  xxxxxx           x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                              xxxxx=               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                           xxxx                                                   ",
   "                                                        xxxx                                                      ",
   "                                                       xx                                                         ",
   "                                               s   xxxxx                                                          ",
   "    @                                        xxxxx                                                                ",
   "                                       xxxxx                                                                      ",
   "                                 xxxx                                                                             ",
   "                          xxxxx                                                                                   ",
   "                      xxx                                                                                         ",
   "                    xxx                                                                                           ",
   "                  xxx                                                                                             ",
   "                xxx                                                                                               ",
   "              xxx                                                                                                 ",
   "           xxxx                                                                                                   ",
   "          xx                                                                                       o   o  o  o    ",
   "         xx                                                                       o  o   o  o  o  o  o  o  o   o  ",
   "        xx                                                                    o  o  o  o   o  o  o  o  o  o  o  o ",
   "xxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                   @                                                                                              ",
   "                                                                                                                  ",
   "           xxxxxxxxxxxx        x          x       xxxxxxxxx                                                       ",
   "                 x             x          x       x                                                               ",
   "                 x             x          x       x                                                               ",
   "                 x             xxxxxxxxxxxx       xxxxxx                                                          ",
   "                 x             x          x       x                                                               ",
   "                 x             x          x       x                                                               ",
   "                 x             x          x       xxxxxxxxx                                                       ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                 xxxxxxxxxx    xxxx       x     xxxxxxxx                                                          ",
   "                 x             x   x      x     x       xx                                                        ",
   "                 x             x    xx    x     x        xx                                                       ",
   "                 x             x      x   x     x         x                                                       ",
   "                 xxxxxxx       x       x  x     x         x                                                       ",
   "                 x             x        x x     x        xx                                                       ",
   "                 x             x         xx     x      xx                                                         ",
   "                 xxxxxxxxxx    x          x     xxxxxxx                                                           ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     ",
   "                                                                                                                  ",
   "                                                                                                                  "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;